# Generated by Django 3.1.7 on 2021-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures_app', '0004_category_location_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(related_name='trips', to='adventures_app.Category'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(verbose_name='Days Long:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='picture',
            field=models.ImageField(blank=True, default='default_trip.jfif', null=True, upload_to='trips'),
        ),
    ]
