# Generated by Django 3.1.7 on 2021-07-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures_app', '0006_auto_20210731_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='trips', to='adventures_app.Category', verbose_name='Categories'),
        ),
    ]
